config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/show'
  # root to: "pages#home"
  root to: redirect('/home')
  get 'home', to: 'pages#home'
  devise_for :users, controllers: { profiles: 'profiles' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :dimensions do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[show destroy]
  ## Custom routes for profile
  resource :profile, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dimension
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :guests, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..10 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dimensions
  validates :name, presence: true, uniqueness: true
end

app/models/dimension.rb
class Dimension < ApplicationRecord
  has_many :bookings
  belongs_to :category
  validates :title, presence: true
  validates :description, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :dimensions, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ## May be needed for devise --info https://gist.github.com/withoutwax/46a05861aa4750384df971b641170407
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :first_name, :last_name, :owner, :client)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookings = Booking.all
  end

  def new
    @dimension = Dimension.find(params[:dimension_id])
    @booking = Booking.new
    
    #method to get booked dates in my dimension
    #go to @dimension and check all the bookings, and save all the bookings to an hash
    @booked_dates = []
      @dimension.bookings.map do |booking|
       @booked_dates.push({ from: booking.start_date, to: booking.end_date })
    end
  end

  def create
    start_date, end_date = params[:booking][:start_date].split("to")
    @dimension = Dimension.find(params[:dimension_id])
    @booking = Booking.new(bookings_params)
    @booking.start_date = start_date
    @booking.end_date = end_date
    @booking.dimension = @dimension
    @booking.user = current_user

    if @booking.save
      redirect_to booking_path(@booking.id), notice: 'Booking was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bookings = Booking.all
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])

    @booking.destroy
    redirect_to dimension_path, :notice => "Successfully destroyed booking."
  end

  private
  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :perks, :guests)
  end
end

app/controllers/dimensions_controller.rb
class DimensionsController < ApplicationController
  before_action :set_dimension, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /dimensions
  def index
    dimension_search
  end


  def dimension_search
    @dimensions = Dimension.all
    if params[:query].present?
      sql_subquery = <<~SQL
        dimensions.title @@ :query
        OR dimensions.description @@ :query
        OR categories.name @@ :query
      SQL
      @dimensions = @dimensions.joins(:category).where(sql_subquery, query: params[:query])
    end
  end

  # GET /dimensions/:id
  def show
    @booking = Booking.new
  end

  # GET /dimensions/new
  def new
    @dimension = Dimension.new
  end

  # GET /dimensions/:id/edit
  def edit
  end

  # POST /dimensions
  def create
    @user = current_user
    @dimension = Dimension.new(dimension_params)
    @dimension.user_id = current_user.id
    @dimension.category_id = params[:dimension][:category_id]
    if @dimension.save
      redirect_to @dimension, notice: 'Dimension was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dimensions/:id
  def update
    if @dimension.update(dimension_params)
      redirect_to @dimension, notice: 'Dimension was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /dimensions/:id
  def destroy
    @dimension.destroy
    redirect_to dimensions_url, notice: 'Dimension was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dimension
    @dimension = Dimension.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dimension_params
    params.require(:dimension).permit(:title, :description, :reviews, :category_id, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @categories = Category.all
    @dimensions = Dimension.all
    render :layout => false
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @bookings = Booking.all
    @dimensions = Dimension.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@dimension, booking] do |f| %>
<%= f.input :start_date,
            as: :string,
            input_html: { data: { controller: "datepicker", range: "true", datepicker_disable: @booked_dates  } } %>
<%= f.input :end_date,
            as: :hidden %>
<%= f.input :guests %>
<%= f.input :perks %>
<%= f.submit "Submit", class: "btn btn-purple" %>
<% end %>

app/views/bookings/index.html.erb
<h1>Bookings#show</h1>

<% @bookings.each do |b| %>
  <p> Thanks <%= b.user_id %> for your booking</p>
  <p> You have booked <%= b.dimension_id %></p>
  <p> Starting on: <%= b.start_date %> and finishing on: <%= b.end_date %></p>
  <p> The number of guests will be: <%= b.guests %> </p>
  <p> And the perks: <%= b.perks %></p>
<% end %>

app/views/bookings/new.html.erb
<div class= "form col-4 col-md-10">
  <h1>Make a new booking</h1>
<%= render "bookings/form", booking: @booking%>
</div>

app/views/bookings/show.html.erb
  <div class="confirmationnn">
    <h1>Booking Confirmed!</h1>

    <div class="card-confo d-flex p-10">
      <%= cl_image_tag @booking.dimension.photo.key, height: 150, width: 150, crop: :fill %>
      <div class="card-trip-infos p-10">
        <div>
          <h2>You have booked <%= @booking.dimension.title%></h2>

          <p> Starting on: <%= @booking.start_date %> and finishing on: <%= @booking.end_date %></p>
          <p> You booked the perks: <%= @booking.perks %></p>

        </div>
        <p class="card-trip-pricing">Guests: <%= @booking.guests%></p>
      </div>
    </div>
  </div>

app/views/dimensions/_form.html.erb
<%= simple_form_for [dimension] do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.association :category, as: :radio_buttons, prompt: "" %>
<%= f.input :photo, as: :file %>
<%= f.submit "Submit", class: "btn btn-purple" %>
<% end %>

app/views/dimensions/edit.html.erb
 <%= render "dimensions/form", dimension: @dimension %>
 

app/views/dimensions/index.html.erb
<%= render "shared/search" %>
  <div class="row justify-content-center">
    <h1>Our offers in Dimensional experiences</h1>
    <hr>


        <div id="dimensions">
          <% if @dimensions.any? %>
             <%= render "shared/card" %>
          <% else %>
            <em>Sorry, no dimensions available.</em>
          <% end %>
        </div>
  </div>

app/views/dimensions/new.html.erb
<div class= "form col-4 col-md-10">
  <%= render "dimensions/form", dimension: @dimension %>
</div>

app/views/dimensions/show.html.erb
  <div class="show-banner" style="background-image: url(<%= cl_image_path @dimension.photo.key %>);">

  </div>

  <div class="show-content col-12">
    <div class="show-des col-sm-10 col-lg-7">
        <h1 class = "align-middle"><%= @dimension.title %></h2>
        <div class="card-show">
          <div class="card-show-infos">
            <h2> Category : <%= @dimension.category.name %></h2>
            <h3> <i class="fa-solid fa-rocket"></i>  What can you expect?</h1>
            <p> <%= @dimension.description %></p>
            
          </div>
          <%= link_to "Edit the dimension", edit_dimension_path %>
        </div>
    </div>

    <div class="show-booking col-sm-10 col-lg-4 col-xl-4 mb-6">
      <div class="booking-frame">
        <h3>Book this Dimension</h3>
        <%= render "bookings/form", booking: @booking%>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DimensionalHaul</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><% notice %></p>
       <p class="alert"><% alert %></p>
       <%= render "shared/flashes" %>

    <%= render "shared/navbar" %>
    <div class="container col-12">
      <div class="container-header">
        <%# do we need anything in a header? %>
      </div>

      <div class="container-content">
        <div class="row justify-content-center">
          <div class="col-12">
            <%= yield %>
          </div>
        </div>
      </div>

    </div>
    <div class="footer mt-auto py-3">
      <div class="footer-links">
        <a href="https://github.com/fpalou/Dimensional_Haul"><i class="fab fa-github"></i></a>
        <a href="https://dimensional-haul-623e2c8f5718.herokuapp.com/"><i class="fab fa-k"></i></a>
        <a href="https://www.figma.com/file/6n1gVK8bOPRqLdhaz4mB2D"><i class="fa-solid fa-pen-fancy"></i></a>
      </div>
      <div class="footer-copyright">
        <p>Infinite realities, infinite possibilities 🚀 by the Dimensional Haul</p>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dimensional Haul</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="home-page">
    <%= render "shared/banner" %>
    <div class="home-info">
      <div class="row">
        <div class="col-12 ">
          <h3>Discover all possibilities</h3>
        </div>
  <% i = 0 %>
        <% @dimensions.each do |dimension| %>
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card home-card mt-3 mr-3">
              <% if dimension.photo.key %>
                <%= cl_image_tag dimension.photo.key, height: 400, width: 400, crop: :fill, class: "card-img-top" %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= dimension.title %></h5>
                <p class="card-text"><%= dimension.description %></p>
                <%= link_to "Show", dimension_path(dimension), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
          <% i += 1 %>
          <%break if i > 2 %>
        <% end %>
      </div>
      <%# <div class="home-info">
        <h3>Here goes some fancy page info</h3>
      </div> %>
    </div>
      <div class="footer mt-auto py-3">
        <div class="footer-links">
          <a href="https://github.com/fpalou/Dimensional_Haul"><i class="fab fa-github"></i></a>
          <a href="https://dimensional-haul-623e2c8f5718.herokuapp.com/"><i class="fab fa-k"></i></a>
          <a href="https://www.figma.com/file/6n1gVK8bOPRqLdhaz4mB2D"><i class="fa-solid fa-pen-fancy"></i></a>
        </div>
        <div class="footer-copyright">
          <p>Infinite realities, infinite possibilities 🚀 by the Dimensional Haul</p>
        </div>
      </div>
    </body>
  </html>

app/views/profiles/show.html.erb
<div>

  <div class="d-flex col-12">
    <div class="row">
      <div class="col-8">
        <% if @user.owner?%>
          <h2>Here are your dimensions</h2>
        <%= render "shared/user_dimensions_index" %>
        <% end %>
      </div>
    </div>


    <div class="welcome-profile col-3">
      <h2> Hi <%= @user.first_name %></h2>
      <%# <img class="profile-img" src="https://res.cloudinary.com/dckwlb2by/image/upload/v1700818534/profile2_qipz7k.png" alt="profile-photo"> %>
        <div class="card-profile">
          <p>Name: <%= @user.first_name %></p>
          <p>Email: <%= @user.email %></p>
          <% if @user.owner? && @user.client? %>
            <p>Status: owner and client</p>
            <% elsif @user.client? %>
              <p>Status: client</p>
            <% else %>
            <p>Status: owner</p>
            <% end %>
        </div>
    
      <%= link_to "Create a new Dimension", new_dimension_path, class: "btn btn-purple" %>
    </div>
    </div>
  </div>

       <div class="row">
        <% if @user.client? %>
        <h2>These are your booked Dimensional trips</h2>
        <%= render "shared/user_bookings_index" %>
        <% end %>
      </div>
      
</div>

app/views/shared/_banner.html.erb
<div class="cover-container d-flex w-100 p-3 mx-auto flex-column banner-style justify-content-center" data-controller="home-banner">
  <main class="px-3 banner-text-layout">
    <h1 class="fadee">Dimensional Haul</h1>
    <p class="lead fadeee"></p>
    <%= link_to "STEP THROUGH", dimensions_path, class: "btn btn-lg fw-bold border-white",
    id: "banner-btn",
    data: { action: "mouseover->home-banner#zoom" } %>
  </main>

</div>

app/views/shared/_card.html.erb
<div class="container">
  <% @dimensions.each.with_index do |dimension, index| %>
    <% if index % 3 == 0 %>
      <div class="row">
    <% end %>
    <div class="col-md-4 col-lg-4 col-xl-4 mb-4">
      <div class="card-product col-lg col-xl col-3 mt-4">
        <%= cl_image_tag dimension.photo.key %>
        <div class="card-product-infos">
          <h2><%= link_to dimension.title, dimension_path(dimension.id) %></h2>
          <p><%= dimension.description %></p>
          <h3> <%= dimension.category.name %></h3>
        </div>
      </div>
    </div>
    <% if (index + 1) % 3 == 0 || index == @dimensions.size - 1 %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 <%= notice %> </span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><strong>Oops!</strong> 😱 <%= alert %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-auto py-3">
  <div class="footer-links">
    <a href="https://github.com/fpalou/Dimensional_Haul"><i class="fab fa-github"></i></a>
    <a href="https://dimensional-haul-623e2c8f5718.herokuapp.com/"><i class="fab fa-k"></i></a>
    <a href="https://www.figma.com/file/6n1gVK8bOPRqLdhaz4mB2D"><i class="fa-solid fa-pen-fancy"></i></a>
  </div>
  <div class="footer-contact">
    <p> Contact us <i class="fa-solid fa-envelope"></i></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <img src="https://res.cloudinary.com/dckwlb2by/image/upload/v1700817985/logo5-dimension.png" alt="logo">
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="flex-column">
        <h1 class="justify-content-center">Dimensional Haul</h1>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%# <%= link_to "Create Dimension", new_dimension_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All dimensions", dimensions_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
              <%= link_to profile_path do%>
                <img src="https://res.cloudinary.com/dckwlb2by/image/upload/v1700818534/profile2_qipz7k.png" alt="avatar" class="avatar dropdown-toggle" aria-haspopup='true' aria-expanded='false'>
              <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: dimensions_path, method: :get, class: "d-flex" do |form|%>
      <%= form.text_field :start_date,
            as: :string,
            value: params[:start_date],
            class: "form-control",
            placeholder: "What's your start date?",
            data: { controller: "datepicker", range: "true" } %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "What are you looking for?"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-purple" %>
    <% end %>
  </div>
</div>

app/views/shared/_user_bookings_index.html.erb
<div class="booking-table">
<table class="table col-12">
  <% if @bookings.where(user_id: @user.id).empty? %>
            <p>You have not booked anything yet.</p>
            <%= link_to "Explore our dimensions", dimensions_path, class: "btn btn-teal" %>
  <% else %>
    <thead class="thead-dark">
      <tr>
        <th scope="col">Booking id</th>
        <th scope="col">Dimension selected</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Guests Number</th>
        <th scope="col">Your perks</th>
      </tr>
    </thead>
    <tbody class="booking-rows" >
    
    <% @bookings.where(user_id: @user.id).each do |booking| %>
        <tr>
          <th scope="row"><%= booking.id %></th>
          <td><%= booking.dimension.title %></td>
          <td><%= booking.start_date %></td>
          <td><%= booking.end_date %></td>
          <td><%= booking.guests%></td>
          <td><%= booking.perks %></td>
        </tr>
    <% end %>
  
  </tbody>
  <% end %>
</table>
</div>

app/views/shared/_user_dimensions_index.html.erb
<div>
  <% if @user.owner? %>
    <div class="d-flex flex-wrap">
      <% card_count = 0 %>
      <% if @dimensions.where(user_id: @user.id).empty? %>
        <!-- Display message if no dimensions found -->
        <div class="col-12 mb-4">
          <div class="card-dimension-profile col-lg col-xl col-3">
            <div class="card-product-infos">
              <p>Create your first dimension so that others can rent it!</p>
              <%= link_to "Create Dimension", new_dimension_path, class: "btn btn-teal" %>
            </div>
          </div>
        </div>
      <% else %>
        <% @dimensions.where(user_id: @user.id).each do |dimension| %>
          <% card_count += 1 %>
          <div class="col-md-4 col-lg-3 col-xl-3 mb-4">
            <div class="card-dimension-profile col-lg col-xl col-3">
              <div class="card-product-infos">
              <%= cl_image_tag dimension.photo.key %>
              <br>
                <h2><%= dimension.title %></h2>
              </div>
            </div>
          </div>
          <% if card_count % 3 == 0 %>
            <!-- Start a new row after every third card -->
            <div class="w-100"></div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="d-none">
      <!-- Hidden content for non-owners -->
      <p>Not an owner</p>
    </div>
  <% end %>
</div>